### ISSUE TITLE
Deploy release is broken

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo-fdroid#4]
CI job crash with error

```
00:17.538  CRITICAL: Unknown exception found!
00:17.540  Traceback (most recent call last):
00:17.540    File "/usr/bin/fdroid", line 164, in <module>
00:17.540      main()
00:17.540    File "/usr/bin/fdroid", line 138, in main
00:17.540      mod.main()
00:17.540    File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1950, in main
00:17.540      archapks, cc = process_apks(apkcache, repodirs[1], knownapks, options.use_date_from_apk)
00:17.540    File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1445, in process_apks
00:17.540      use_date_from_apk, ada, True)
00:17.540    File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1318, in process_apk
00:17.540      apk = scan_apk(apkfile)
00:17.540    File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1053, in scan_apk
00:17.540      scan_apk_androguard(apk, apk_file)
00:17.540    File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1270, in scan_apk_androguard
00:17.540      feature = str(item.attrib['{' + xml.nsmap['android'] + '}name'])
00:17.540    File "src/lxml/etree.pyx", line 2457, in lxml.etree._Attrib.__getitem__
00:17.540  KeyError: '{http://schemas.android.com/apk/res/android}name'
```

http://ci.cgeo.org/view/Fdroid/job/Publish%20FDroid%20-%20RELEASE/35/console

Blocks: https://github.com/cgeo/cgeo/issues/6956

**Comment by kumy** [comment]
If I remove following files from the archives directory it works:

```
archive/cgeo-release-2016.03.06.apk
archive/cgeo-release-2016.05.08.apk
archive/cgeo-release-2016.06.09.apk
archive/cgeo-release-2016.04.12.apk
```

**Comment by kumy** [comment]
I don't know what's wrong with those apk, let's remove them as they are quite old anyway.
